st = input('Digite algo: ')
print('o tipo primitivo é ', type(st))
print('é um número? ', st.isnumeric())
print('só tem espaço? ', st.isspace())
print('é alfabetico? ', st.isalpha())
print('é alfanumérico? ', st.isalnum())
print('esta em maiúsculo? ', st.islower())
print('esta em minusculo? ', st.isupper())
print('esta capitalizado? ', st.istitle())
